---
kind: pipeline
type: docker
name: default
trigger:
  event:
    exclude:
    - pull_request

steps:
- name: setup-general
  image: allgreed/nix:2.3.6
  commands:
  - echo -n "latest,preview$DRONE_COMMIT_SHA" > .tags

#- name: container-backend
#  image: allgreed/nix:2.3.6
#  commands:
#  - cd back
#  - nix-shell --quiet --run 'make create-container'
#  - cp $(readlink -f result) docker-image.tar.gz

# TODO: figure out how to load the tar

- name: build-frontend
  image: node:13
  commands:
  - cd front
  - npm install
  - npm run build

- name: build-and-push-frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: allgreed/big-pairing-front
    context: ./front
    dockerfile: ./front/Dockerfile
  when:
    branch:
    - master

- name: deploy
  image: allgreed/nix:2.3.6
  environment:
    NOMAD_URL:
      from_secret: nomad_url
  commands:
  - VERSION=preview$DRONE_COMMIT_SHA ./deploy.nomad.tpl > deploy.nomad
  - NOMAD_URL=$NOMAD_URL nix-shell --quiet --run "nomad job run -address=$NOMAD_URL deploy.nomad"
  when:
    branch:
    - master
