---
kind: pipeline
type: docker
name: default
trigger:
  event:
    exclude:
    - pull_request

steps:
- name: setup
  image: nixos/nix:2.3
  commands:
# TODO: how to run nix-shell in a subfolder?
#  - nix-shell --quiet --run 'make setup'
  - echo -n "latest,preview$DRONE_COMMIT_SHA" > .tags

#- name: build
#  image: nixos/nix:2.3
#  commands:
#  - nix-shell --quiet --run 'make build'

#- name: docker  
#  image: plugins/docker
#  settings:
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    repo: allgreed/big-pairing
#  when:
#    branch:
#    - master

- name: deploy
  image: nixos/nix:2.3
  environment:
    NOMAD_URL:
      from_secret: nomad_url
  commands:
  - VERSION=preview$DRONE_COMMIT_SHA ./deploy.nomad.tpl > deploy.nomad
  - nix-shell --quiet --run "nomad job run -address=$NOMAD_URL deploy.nomad"
  when:
    branch:
    - master

#---
#kind: pipeline
#type: docker
#name: pr
#trigger:
#  event:
#    - pull_request
