---
kind: pipeline
type: docker
name: default
trigger:
  event:
    exclude:
    - pull_request

steps:
- name: setup-general
  image: allgreed/nix:2.3.6
  commands:
  - echo -n "latest,preview$DRONE_COMMIT_SHA" > .tags

- name: container-backend
  image: allgreed/nix:2.3.6
  commands:
  - cd back
  - nix-shell --quiet --run 'make create-container'
  - cp $(readlink -f docker-image.tar.gz) ../docker-image.tar.gz # need to persist the image between stages and Drone only mounts CWD, so symlinks would fail
# TODO: move instead of copy to save time!

- name: load-and-store-backend
  image: allgreed/drone-load-and-store
  settings:
    archive: docker-image.tar.gz
    repo: allgreed/big-pairing-back
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master

- name: build-frontend
  image: node:13
  commands:
  - cd front
  - npm install
  - npm run build

- name: build-and-push-frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: allgreed/big-pairing-front
    context: ./front
    dockerfile: ./front/Dockerfile
  when:
    branch:
    - master

- name: deploy
  image: allgreed/nix:2.3.6
  environment:
    NOMAD_URL:
      from_secret: nomad_url
  commands:
  - VERSION=preview$DRONE_COMMIT_SHA ./deploy.nomad.tpl > deploy.nomad
  - NOMAD_URL=$NOMAD_URL nix-shell --quiet --run "nomad job run -address=$NOMAD_URL deploy.nomad"
  when:
    branch:
    - master
